### ISSUE TITLE
Create Icon and diferent size HD images for the Logo

### ISSUE THREAD

**Issue by ozefreitas** [ozefreitas/flordelinha_website#6]
- [x] Create Icon with background
- [x] Create 250x250px with colored background
- [x] Create 250x250px without background
- [x] Create 500x500px with colored background
- [x] Create 500x500px without background

**This needs no new branch neither does for a pull request, changes can be directly merged into `main` from `dev`**

**Comment by amariarodrigues** [comment]
![flor_de_linha_250px](https://github.com/user-attachments/assets/dda91f2d-e61e-4b5b-a140-f4a7e122c79f)
![flor_de_linha_500px](https://github.com/user-attachments/assets/9bc258b1-85af-417f-b136-b943ddad0d31)
![flor_de_linha_no_bg_250px](https://github.com/user-attachments/assets/c85f0725-7fa7-4f3a-89e6-4434627c5036)
![flor_de_linha_no_bg_500px](https://github.com/user-attachments/assets/5a3a11cf-4386-416a-93f6-65029f111878)

Here are the files, the .ico file is not supported here, so I will be sending it to you shortly

**Comment by amariarodrigues** [comment]
Here are the files

[flor_de_linha_logos.zip](https://github.com/user-attachments/files/16474596/flor_de_linha_logos.zip)

**Comment by ozefreitas** [comment]
Ok, they have now been added to the assets and applied to where we wanted. They are stored so we can use them at will later.
Still to merge into `main`, but will close this Issue, as it will be merged together with #4
